@startuml Azul classes
class Container{
    + container[BLUE, YELLOW, RED, BLACK, BLUESTAR] : Array[20,20,20,20,20]
    

}
note right: those are Array[i] maximums
Container o-- Bag
class Bag{
    + setDisc(Disc)

}

Container o-- DiscardPile
class DiscardPile{
    + getBrokenTiles(BroktenTiles)
    + fillUpBag()
}

Container *--Tiles
enum Tiles{
    BLUE
    YELLOW
    RED
    BLACK
    BLUESTAR
}

Container o-- Disc
class Disc{
    + getSameColoredTiles(Disc)
    + dropTilesToCenter()
    + setDisc()
}
Container o-- CenterPool
CenterPool --o Disc
class CenterPool{
    + getSameColoredTiles(Tile)
}



Container o-- PlayerBoard
class PlayerBoard{
    + points : int
    __methods__
    + calculatePoints(Wall wall, SampleTileRow str)

}

PlayerBoard *-- SampleTileRow
class SampleTileRow{
    row[] : Array[Tile]
    __setter__
    setRow()
    __getter__
    getRow()

}
note left: setter makes all the rows (0-4)

PlayerBoard *-- Wall
class Wall{
    wall[4][4] : Array[][]
}

PlayerBoard *-- BrokenTiles
class BrokenTiles{
    + brokenTiles[6] : Array[Tile]
    __setter__
    + addBrokenTiles()

}

@enduml